// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter v122ff0 = 7,
 parameter v3daed4 = 1,
 parameter v183a43 = 1,
 parameter vbad1db = 1,
 parameter v29b1e3 = 1,
 parameter vd02bb0 = 1,
 parameter v9e2981 = 1,
 parameter v62512a = 1,
 parameter v2eac33 = 1
) (
 input vd7f694,
 output v3dc8fa,
 output v470770,
 output v7479e8,
 output v993750,
 output vc06406,
 output vfff4aa,
 output vfb3cf5,
 output ve8d7e3,
 output [0:3] vinit
);
 localparam p0 = v3daed4;
 localparam p2 = v122ff0;
 localparam p36 = v62512a;
 localparam p37 = v29b1e3;
 localparam p38 = v183a43;
 localparam p39 = vbad1db;
 localparam p40 = vd02bb0;
 localparam p41 = v9e2981;
 localparam p42 = v2eac33;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w43;
 wire w44;
 wire w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 wire w50;
 wire w51;
 wire w52;
 wire w53;
 wire w54;
 wire w55;
 wire w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire w65;
 wire w66;
 wire w67;
 wire w68;
 wire w69;
 wire w70;
 wire w71;
 wire w72;
 wire w73;
 wire w74;
 wire w75;
 wire w76;
 wire w77;
 wire w78;
 wire w79;
 wire w80;
 wire w81;
 wire w82;
 wire w83;
 wire w84;
 wire w85;
 wire w86;
 assign w1 = vd7f694;
 assign v3dc8fa = w80;
 assign v470770 = w81;
 assign v7479e8 = w82;
 assign v993750 = w83;
 assign vc06406 = w84;
 assign vfff4aa = w85;
 assign vfb3cf5 = w86;
 assign w49 = w48;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 assign w54 = w48;
 assign w54 = w49;
 assign w54 = w50;
 assign w54 = w51;
 assign w54 = w52;
 assign w54 = w53;
 assign w55 = w48;
 assign w55 = w49;
 assign w55 = w50;
 assign w55 = w51;
 assign w55 = w52;
 assign w55 = w53;
 assign w55 = w54;
 assign w56 = w48;
 assign w56 = w49;
 assign w56 = w50;
 assign w56 = w51;
 assign w56 = w52;
 assign w56 = w53;
 assign w56 = w54;
 assign w56 = w55;
 assign w57 = w48;
 assign w57 = w49;
 assign w57 = w50;
 assign w57 = w51;
 assign w57 = w52;
 assign w57 = w53;
 assign w57 = w54;
 assign w57 = w55;
 assign w57 = w56;
 assign w58 = w48;
 assign w58 = w49;
 assign w58 = w50;
 assign w58 = w51;
 assign w58 = w52;
 assign w58 = w53;
 assign w58 = w54;
 assign w58 = w55;
 assign w58 = w56;
 assign w58 = w57;
 assign w59 = w48;
 assign w59 = w49;
 assign w59 = w50;
 assign w59 = w51;
 assign w59 = w52;
 assign w59 = w53;
 assign w59 = w54;
 assign w59 = w55;
 assign w59 = w56;
 assign w59 = w57;
 assign w59 = w58;
 assign w60 = w48;
 assign w60 = w49;
 assign w60 = w50;
 assign w60 = w51;
 assign w60 = w52;
 assign w60 = w53;
 assign w60 = w54;
 assign w60 = w55;
 assign w60 = w56;
 assign w60 = w57;
 assign w60 = w58;
 assign w60 = w59;
 assign w61 = w48;
 assign w61 = w49;
 assign w61 = w50;
 assign w61 = w51;
 assign w61 = w52;
 assign w61 = w53;
 assign w61 = w54;
 assign w61 = w55;
 assign w61 = w56;
 assign w61 = w57;
 assign w61 = w58;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w48;
 assign w62 = w49;
 assign w62 = w50;
 assign w62 = w51;
 assign w62 = w52;
 assign w62 = w53;
 assign w62 = w54;
 assign w62 = w55;
 assign w62 = w56;
 assign w62 = w57;
 assign w62 = w58;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w63 = w48;
 assign w63 = w49;
 assign w63 = w50;
 assign w63 = w51;
 assign w63 = w52;
 assign w63 = w53;
 assign w63 = w54;
 assign w63 = w55;
 assign w63 = w56;
 assign w63 = w57;
 assign w63 = w58;
 assign w63 = w59;
 assign w63 = w60;
 assign w63 = w61;
 assign w63 = w62;
 assign w64 = w48;
 assign w64 = w49;
 assign w64 = w50;
 assign w64 = w51;
 assign w64 = w52;
 assign w64 = w53;
 assign w64 = w54;
 assign w64 = w55;
 assign w64 = w56;
 assign w64 = w57;
 assign w64 = w58;
 assign w64 = w59;
 assign w64 = w60;
 assign w64 = w61;
 assign w64 = w62;
 assign w64 = w63;
 assign w65 = w48;
 assign w65 = w49;
 assign w65 = w50;
 assign w65 = w51;
 assign w65 = w52;
 assign w65 = w53;
 assign w65 = w54;
 assign w65 = w55;
 assign w65 = w56;
 assign w65 = w57;
 assign w65 = w58;
 assign w65 = w59;
 assign w65 = w60;
 assign w65 = w61;
 assign w65 = w62;
 assign w65 = w63;
 assign w65 = w64;
 assign w66 = w48;
 assign w66 = w49;
 assign w66 = w50;
 assign w66 = w51;
 assign w66 = w52;
 assign w66 = w53;
 assign w66 = w54;
 assign w66 = w55;
 assign w66 = w56;
 assign w66 = w57;
 assign w66 = w58;
 assign w66 = w59;
 assign w66 = w60;
 assign w66 = w61;
 assign w66 = w62;
 assign w66 = w63;
 assign w66 = w64;
 assign w66 = w65;
 assign w67 = w48;
 assign w67 = w49;
 assign w67 = w50;
 assign w67 = w51;
 assign w67 = w52;
 assign w67 = w53;
 assign w67 = w54;
 assign w67 = w55;
 assign w67 = w56;
 assign w67 = w57;
 assign w67 = w58;
 assign w67 = w59;
 assign w67 = w60;
 assign w67 = w61;
 assign w67 = w62;
 assign w67 = w63;
 assign w67 = w64;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w48;
 assign w68 = w49;
 assign w68 = w50;
 assign w68 = w51;
 assign w68 = w52;
 assign w68 = w53;
 assign w68 = w54;
 assign w68 = w55;
 assign w68 = w56;
 assign w68 = w57;
 assign w68 = w58;
 assign w68 = w59;
 assign w68 = w60;
 assign w68 = w61;
 assign w68 = w62;
 assign w68 = w63;
 assign w68 = w64;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w48;
 assign w69 = w49;
 assign w69 = w50;
 assign w69 = w51;
 assign w69 = w52;
 assign w69 = w53;
 assign w69 = w54;
 assign w69 = w55;
 assign w69 = w56;
 assign w69 = w57;
 assign w69 = w58;
 assign w69 = w59;
 assign w69 = w60;
 assign w69 = w61;
 assign w69 = w62;
 assign w69 = w63;
 assign w69 = w64;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w48;
 assign w70 = w49;
 assign w70 = w50;
 assign w70 = w51;
 assign w70 = w52;
 assign w70 = w53;
 assign w70 = w54;
 assign w70 = w55;
 assign w70 = w56;
 assign w70 = w57;
 assign w70 = w58;
 assign w70 = w59;
 assign w70 = w60;
 assign w70 = w61;
 assign w70 = w62;
 assign w70 = w63;
 assign w70 = w64;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w48;
 assign w71 = w49;
 assign w71 = w50;
 assign w71 = w51;
 assign w71 = w52;
 assign w71 = w53;
 assign w71 = w54;
 assign w71 = w55;
 assign w71 = w56;
 assign w71 = w57;
 assign w71 = w58;
 assign w71 = w59;
 assign w71 = w60;
 assign w71 = w61;
 assign w71 = w62;
 assign w71 = w63;
 assign w71 = w64;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w72 = w48;
 assign w72 = w49;
 assign w72 = w50;
 assign w72 = w51;
 assign w72 = w52;
 assign w72 = w53;
 assign w72 = w54;
 assign w72 = w55;
 assign w72 = w56;
 assign w72 = w57;
 assign w72 = w58;
 assign w72 = w59;
 assign w72 = w60;
 assign w72 = w61;
 assign w72 = w62;
 assign w72 = w63;
 assign w72 = w64;
 assign w72 = w65;
 assign w72 = w66;
 assign w72 = w67;
 assign w72 = w68;
 assign w72 = w69;
 assign w72 = w70;
 assign w72 = w71;
 assign w73 = w48;
 assign w73 = w49;
 assign w73 = w50;
 assign w73 = w51;
 assign w73 = w52;
 assign w73 = w53;
 assign w73 = w54;
 assign w73 = w55;
 assign w73 = w56;
 assign w73 = w57;
 assign w73 = w58;
 assign w73 = w59;
 assign w73 = w60;
 assign w73 = w61;
 assign w73 = w62;
 assign w73 = w63;
 assign w73 = w64;
 assign w73 = w65;
 assign w73 = w66;
 assign w73 = w67;
 assign w73 = w68;
 assign w73 = w69;
 assign w73 = w70;
 assign w73 = w71;
 assign w73 = w72;
 assign w74 = w48;
 assign w74 = w49;
 assign w74 = w50;
 assign w74 = w51;
 assign w74 = w52;
 assign w74 = w53;
 assign w74 = w54;
 assign w74 = w55;
 assign w74 = w56;
 assign w74 = w57;
 assign w74 = w58;
 assign w74 = w59;
 assign w74 = w60;
 assign w74 = w61;
 assign w74 = w62;
 assign w74 = w63;
 assign w74 = w64;
 assign w74 = w65;
 assign w74 = w66;
 assign w74 = w67;
 assign w74 = w68;
 assign w74 = w69;
 assign w74 = w70;
 assign w74 = w71;
 assign w74 = w72;
 assign w74 = w73;
 assign w75 = w48;
 assign w75 = w49;
 assign w75 = w50;
 assign w75 = w51;
 assign w75 = w52;
 assign w75 = w53;
 assign w75 = w54;
 assign w75 = w55;
 assign w75 = w56;
 assign w75 = w57;
 assign w75 = w58;
 assign w75 = w59;
 assign w75 = w60;
 assign w75 = w61;
 assign w75 = w62;
 assign w75 = w63;
 assign w75 = w64;
 assign w75 = w65;
 assign w75 = w66;
 assign w75 = w67;
 assign w75 = w68;
 assign w75 = w69;
 assign w75 = w70;
 assign w75 = w71;
 assign w75 = w72;
 assign w75 = w73;
 assign w75 = w74;
 assign w76 = w48;
 assign w76 = w49;
 assign w76 = w50;
 assign w76 = w51;
 assign w76 = w52;
 assign w76 = w53;
 assign w76 = w54;
 assign w76 = w55;
 assign w76 = w56;
 assign w76 = w57;
 assign w76 = w58;
 assign w76 = w59;
 assign w76 = w60;
 assign w76 = w61;
 assign w76 = w62;
 assign w76 = w63;
 assign w76 = w64;
 assign w76 = w65;
 assign w76 = w66;
 assign w76 = w67;
 assign w76 = w68;
 assign w76 = w69;
 assign w76 = w70;
 assign w76 = w71;
 assign w76 = w72;
 assign w76 = w73;
 assign w76 = w74;
 assign w76 = w75;
 assign w77 = w48;
 assign w77 = w49;
 assign w77 = w50;
 assign w77 = w51;
 assign w77 = w52;
 assign w77 = w53;
 assign w77 = w54;
 assign w77 = w55;
 assign w77 = w56;
 assign w77 = w57;
 assign w77 = w58;
 assign w77 = w59;
 assign w77 = w60;
 assign w77 = w61;
 assign w77 = w62;
 assign w77 = w63;
 assign w77 = w64;
 assign w77 = w65;
 assign w77 = w66;
 assign w77 = w67;
 assign w77 = w68;
 assign w77 = w69;
 assign w77 = w70;
 assign w77 = w71;
 assign w77 = w72;
 assign w77 = w73;
 assign w77 = w74;
 assign w77 = w75;
 assign w77 = w76;
 assign w78 = w48;
 assign w78 = w49;
 assign w78 = w50;
 assign w78 = w51;
 assign w78 = w52;
 assign w78 = w53;
 assign w78 = w54;
 assign w78 = w55;
 assign w78 = w56;
 assign w78 = w57;
 assign w78 = w58;
 assign w78 = w59;
 assign w78 = w60;
 assign w78 = w61;
 assign w78 = w62;
 assign w78 = w63;
 assign w78 = w64;
 assign w78 = w65;
 assign w78 = w66;
 assign w78 = w67;
 assign w78 = w68;
 assign w78 = w69;
 assign w78 = w70;
 assign w78 = w71;
 assign w78 = w72;
 assign w78 = w73;
 assign w78 = w74;
 assign w78 = w75;
 assign w78 = w76;
 assign w78 = w77;
 assign w79 = w48;
 assign w79 = w49;
 assign w79 = w50;
 assign w79 = w51;
 assign w79 = w52;
 assign w79 = w53;
 assign w79 = w54;
 assign w79 = w55;
 assign w79 = w56;
 assign w79 = w57;
 assign w79 = w58;
 assign w79 = w59;
 assign w79 = w60;
 assign w79 = w61;
 assign w79 = w62;
 assign w79 = w63;
 assign w79 = w64;
 assign w79 = w65;
 assign w79 = w66;
 assign w79 = w67;
 assign w79 = w68;
 assign w79 = w69;
 assign w79 = w70;
 assign w79 = w71;
 assign w79 = w72;
 assign w79 = w73;
 assign w79 = w74;
 assign w79 = w75;
 assign w79 = w76;
 assign w79 = w77;
 assign w79 = w78;
 assign w82 = w46;
 assign w85 = w45;
 ve156d2 #(
  .vc26a97(p0)
 ) v006fdf (
  .v65137a(w3),
  .v9c7873(w43),
  .ve61433(w48)
 );
 ve156d2 v6323d3 (
  .v9c7873(w5),
  .v65137a(w11),
  .ve61433(w72)
 );
 v6a5074 #(
  .v100e1b(p2)
 ) v01053a (
  .v0daa9e(w1),
  .v2efea4(w48)
 );
 ve156d2 vad80ab (
  .v9c7873(w3),
  .v65137a(w4),
  .ve61433(w56)
 );
 ve156d2 vb1ba9f (
  .v9c7873(w4),
  .v65137a(w5),
  .ve61433(w64)
 );
 v18c17a vfb991e (
  .vcbab45(w6),
  .v0e28cb(w44),
  .v3ca442(w45)
 );
 v18c17a vebfb5b (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w43)
 );
 v18c17a v390f5c (
  .vcbab45(w7),
  .v0e28cb(w46),
  .v3ca442(w47)
 );
 ve156d2 #(
  .vc26a97(p38)
 ) v962073 (
  .v65137a(w8),
  .v9c7873(w11),
  .ve61433(w52)
 );
 ve156d2 v67f03e (
  .v9c7873(w9),
  .v65137a(w30),
  .ve61433(w76)
 );
 ve156d2 vb5438c (
  .v9c7873(w8),
  .v65137a(w10),
  .ve61433(w60)
 );
 ve156d2 v791f51 (
  .v65137a(w9),
  .v9c7873(w10),
  .ve61433(w68)
 );
 ve156d2 v25bd7f (
  .v9c7873(w12),
  .v65137a(w13),
  .ve61433(w65)
 );
 ve156d2 v769342 (
  .v65137a(w12),
  .v9c7873(w14),
  .ve61433(w57)
 );
 ve156d2 v69130f (
  .v9c7873(w13),
  .v65137a(w31),
  .ve61433(w73)
 );
 ve156d2 #(
  .vc26a97(p39)
 ) vc199ff (
  .v65137a(w14),
  .v9c7873(w30),
  .ve61433(w49)
 );
 ve156d2 vd87c48 (
  .v9c7873(w15),
  .v65137a(w16),
  .ve61433(w69)
 );
 ve156d2 v75cb8a (
  .v65137a(w15),
  .v9c7873(w17),
  .ve61433(w61)
 );
 ve156d2 v38ed94 (
  .v9c7873(w16),
  .v65137a(w32),
  .ve61433(w77)
 );
 ve156d2 #(
  .vc26a97(p37)
 ) vc7503d (
  .v65137a(w17),
  .v9c7873(w31),
  .ve61433(w53)
 );
 ve156d2 v036201 (
  .v9c7873(w18),
  .v65137a(w19),
  .ve61433(w66)
 );
 ve156d2 v264313 (
  .v65137a(w18),
  .v9c7873(w20),
  .ve61433(w58)
 );
 ve156d2 v0ea980 (
  .v9c7873(w19),
  .v65137a(w33),
  .ve61433(w74)
 );
 ve156d2 #(
  .vc26a97(p40)
 ) v391b02 (
  .v65137a(w20),
  .v9c7873(w32),
  .ve61433(w50)
 );
 ve156d2 v4df79e (
  .v9c7873(w21),
  .v65137a(w22),
  .ve61433(w70)
 );
 ve156d2 vdf83b6 (
  .v65137a(w21),
  .v9c7873(w23),
  .ve61433(w62)
 );
 ve156d2 v489eca (
  .v9c7873(w22),
  .v65137a(w34),
  .ve61433(w78)
 );
 ve156d2 #(
  .vc26a97(p41)
 ) v44ca4d (
  .v65137a(w23),
  .v9c7873(w33),
  .ve61433(w54)
 );
 ve156d2 vbf8d72 (
  .v9c7873(w24),
  .v65137a(w25),
  .ve61433(w67)
 );
 ve156d2 v044aff (
  .v65137a(w24),
  .v9c7873(w26),
  .ve61433(w59)
 );
 ve156d2 v3715f3 (
  .v9c7873(w25),
  .v65137a(w35),
  .ve61433(w75)
 );
 ve156d2 #(
  .vc26a97(p36)
 ) v4ed861 (
  .v65137a(w26),
  .v9c7873(w34),
  .ve61433(w51)
 );
 ve156d2 vf9f68d (
  .v9c7873(w27),
  .v65137a(w28),
  .v965bb0(w47),
  .ve61433(w71)
 );
 ve156d2 vfcc71b (
  .v65137a(w27),
  .v9c7873(w29),
  .ve61433(w63)
 );
 ve156d2 v99bdc4 (
  .v9c7873(w28),
  .v65137a(w44),
  .v965bb0(w45),
  .v47ed3b(w46),
  .ve61433(w79),
  .va879db(w80),
  .v0eab11(w81),
  .v757ca8(w83),
  .vd710bf(w84),
  .v5e9ead(w86)
 );
 ve156d2 #(
  .vc26a97(p42)
 ) v87f838 (
  .v65137a(w29),
  .v9c7873(w35),
  .ve61433(w55)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module ve156d2 #(
 parameter vc26a97 = 0
) (
 input ve61433,
 input v9c7873,
 output va879db,
 output v0eab11,
 output v47ed3b,
 output v757ca8,
 output vd710bf,
 output v965bb0,
 output v5e9ead,
 output v65137a
);
 localparam p24 = vc26a97;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 assign w0 = ve61433;
 assign w1 = ve61433;
 assign w2 = ve61433;
 assign w3 = ve61433;
 assign w4 = ve61433;
 assign w5 = ve61433;
 assign w6 = ve61433;
 assign w7 = ve61433;
 assign w8 = v9c7873;
 assign va879db = w16;
 assign v0eab11 = w17;
 assign v47ed3b = w18;
 assign v757ca8 = w19;
 assign vd710bf = w20;
 assign v965bb0 = w21;
 assign v5e9ead = w22;
 assign v65137a = w23;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 assign w4 = w0;
 assign w4 = w1;
 assign w4 = w2;
 assign w4 = w3;
 assign w5 = w0;
 assign w5 = w1;
 assign w5 = w2;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w0;
 assign w6 = w1;
 assign w6 = w2;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w0;
 assign w7 = w1;
 assign w7 = w2;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w16 = w9;
 assign w17 = w10;
 assign w18 = w11;
 assign w19 = w12;
 assign w20 = w13;
 assign w21 = w14;
 assign w22 = w15;
 v58ed2b #(
  .v71e305(p24)
 ) v8ed6ea (
  .va4102a(w0),
  .vf54559(w8),
  .ve8318d(w9)
 );
 v58ed2b v18f21d (
  .va4102a(w1),
  .vf54559(w9),
  .ve8318d(w10)
 );
 v58ed2b v612bad (
  .va4102a(w2),
  .vf54559(w10),
  .ve8318d(w11)
 );
 v58ed2b vda9cfe (
  .va4102a(w3),
  .vf54559(w11),
  .ve8318d(w12)
 );
 v58ed2b v616ec7 (
  .va4102a(w4),
  .vf54559(w12),
  .ve8318d(w13)
 );
 v58ed2b v1681fd (
  .va4102a(w5),
  .vf54559(w13),
  .ve8318d(w14)
 );
 v58ed2b v2e0e89 (
  .va4102a(w6),
  .vf54559(w14),
  .ve8318d(w15)
 );
 v58ed2b va9e0e6 (
  .va4102a(w7),
  .vf54559(w15),
  .ve8318d(w23)
 );
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
