// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter v122ff0 = 6,
 parameter v3daed4 = 1
) (
 input vd7f694,
 output v3dc8fa,
 output v470770,
 output v7479e8,
 output v993750,
 output vc06406,
 output vfff4aa,
 output vfb3cf5,
 output ve8d7e3,
 output [0:3] vinit
);
 localparam p0 = v3daed4;
 localparam p2 = v122ff0;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 assign w1 = vd7f694;
 assign v3dc8fa = w17;
 assign v470770 = w18;
 assign v7479e8 = w19;
 assign v993750 = w20;
 assign vc06406 = w21;
 assign vfff4aa = w22;
 assign vfb3cf5 = w23;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 ve156d2 #(
  .vc26a97(p0)
 ) v006fdf (
  .v65137a(w3),
  .v0eab11(w8),
  .v965bb0(w9),
  .v9c7873(w10),
  .v5e9ead(w11),
  .ve61433(w12)
 );
 ve156d2 v6323d3 (
  .v9c7873(w5),
  .ve61433(w15),
  .v65137a(w16),
  .va879db(w17),
  .v0eab11(w18),
  .v47ed3b(w19),
  .v757ca8(w20),
  .vd710bf(w21),
  .v965bb0(w22),
  .v5e9ead(w23)
 );
 v6a5074 #(
  .v100e1b(p2)
 ) v01053a (
  .v0daa9e(w1),
  .v2efea4(w12)
 );
 ve156d2 vad80ab (
  .v9c7873(w3),
  .v65137a(w4),
  .ve61433(w13)
 );
 ve156d2 vb1ba9f (
  .v9c7873(w4),
  .v65137a(w5),
  .ve61433(w14)
 );
 v18c17a vfb991e (
  .vcbab45(w6),
  .v0e28cb(w8),
  .v3ca442(w9)
 );
 v18c17a vebfb5b (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w10)
 );
 v18c17a v390f5c (
  .vcbab45(w7),
  .v0e28cb(w11),
  .v3ca442(w16)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module ve156d2 #(
 parameter vc26a97 = 0
) (
 input ve61433,
 input v9c7873,
 output va879db,
 output v0eab11,
 output v47ed3b,
 output v757ca8,
 output vd710bf,
 output v965bb0,
 output v5e9ead,
 output v65137a
);
 localparam p24 = vc26a97;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 assign w0 = ve61433;
 assign w1 = ve61433;
 assign w2 = ve61433;
 assign w3 = ve61433;
 assign w4 = ve61433;
 assign w5 = ve61433;
 assign w6 = ve61433;
 assign w7 = ve61433;
 assign w8 = v9c7873;
 assign va879db = w16;
 assign v0eab11 = w17;
 assign v47ed3b = w18;
 assign v757ca8 = w19;
 assign vd710bf = w20;
 assign v965bb0 = w21;
 assign v5e9ead = w22;
 assign v65137a = w23;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 assign w4 = w0;
 assign w4 = w1;
 assign w4 = w2;
 assign w4 = w3;
 assign w5 = w0;
 assign w5 = w1;
 assign w5 = w2;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w0;
 assign w6 = w1;
 assign w6 = w2;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w0;
 assign w7 = w1;
 assign w7 = w2;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w16 = w9;
 assign w17 = w10;
 assign w18 = w11;
 assign w19 = w12;
 assign w20 = w13;
 assign w21 = w14;
 assign w22 = w15;
 v58ed2b #(
  .v71e305(p24)
 ) v8ed6ea (
  .va4102a(w0),
  .vf54559(w8),
  .ve8318d(w9)
 );
 v58ed2b v18f21d (
  .va4102a(w1),
  .vf54559(w9),
  .ve8318d(w10)
 );
 v58ed2b v612bad (
  .va4102a(w2),
  .vf54559(w10),
  .ve8318d(w11)
 );
 v58ed2b vda9cfe (
  .va4102a(w3),
  .vf54559(w11),
  .ve8318d(w12)
 );
 v58ed2b v616ec7 (
  .va4102a(w4),
  .vf54559(w12),
  .ve8318d(w13)
 );
 v58ed2b v1681fd (
  .va4102a(w5),
  .vf54559(w13),
  .ve8318d(w14)
 );
 v58ed2b v2e0e89 (
  .va4102a(w6),
  .vf54559(w14),
  .ve8318d(w15)
 );
 v58ed2b va9e0e6 (
  .va4102a(w7),
  .vf54559(w15),
  .ve8318d(w23)
 );
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule
//---- Top entity
module v6a5074 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v6a5074_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v6a5074_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v18c17a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v18c17a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: 2-bits input xor gate. Verilog implementation
//---------------------------------------------------

module v18c17a_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
